  insert into Products (product_name, price, quantity, category) values
  ('Chocolate Coconut Granola', 3.79, 82, 'Food - Cereals'),
  ('Electrolyte Water Bottle', 34.99, 21, 'Fitness'),
  ('Roasted Red Pepper Sauce', 3.29, 62, 'Food - Sauces'),
  ('Lentils', 2.99, 62, 'Food - Grains'),
  ('Suede Ankle Booties', 79.99, 71, 'Clothing - Footwear'),
  ('Set of Silicone Cooking Utensils', 29.99, 1, 'Kitchen'),
  ('Cereal Dispenser with Portion Control', 24.99, 77, 'Kitchen'),
  ('Coconut Cashew Yogurt', 1.99, 3, 'Food - Dairy Alternatives'),
  ('Nutritional Yeast', 3.59, 52, 'Food - Pantry'),
  ('Herb Garden Planter Box', 49.99, 98, 'Garden'),
  ('Berry Smoothie Mix', 4.99, 58, 'Food - Frozen Foods'),
  ('Garlic Parmesan Roasted Nuts', 4.89, 70, 'Food - Nuts'),
  ('Cauliflower Pizza Crust', 5.99, 5, 'Food - Frozen Foods'),
  ('Chocolate Covered Pretzels', 3.29, 45, 'Food - Snacks'),
  ('High-Quality Yoga Mat', 34.99, 98, 'Fitness'),
  ('Bike Helmet', 34.99, 97, 'Bicycles'),
  ('Vanilla Ice Cream', 4.99, 26, 'Food - Frozen Foods'),
  ('Teriyaki Stir-Fry Sauce', 3.49, 98, 'Food - Condiments'),
  ('Adjustable Pedicure Footrest', 39.99, 81, 'Beauty'),
  ('Saffron Rice Mix', 2.99, 1, 'Food - Grains'),
  ('Compact Portable Grill', 79.99, 66, 'Outdoor'),
  ('Camping Chair with Cooler', 49.99, 68, 'Outdoor'),
  ('Adjustable Kitchen Broom Stand', 14.99, 38, 'Home'),
  ('Electric Screwdriver', 59.99, 17, 'Tools'),
  ('Beef Tacos', 5.49, 88, 'Food - Meat'),
  ('Digital Alarm Clock', 19.99, 97, 'Home'),
  ('Savory Snack Mix', 4.49, 15, 'Food - Snacks'),
  ('Wall-Mounted Spice Rack', 39.99, 50, 'Kitchen'),
  ('Wrap Jumpsuit', 54.99, 2, 'Clothing - Jumpsuits'),
  ('Whole Roasted Chicken', 9.99, 72, 'Food - Meats'),
  ('Cinnamon Sugar Mix', 1.49, 42, 'Food - Baking'),
  ('Rain Jacket', 64.99, 43, 'Clothing'),
  ('Organic Green Lentils', 3.99, 38, 'Food - Grocery'),
  ('Lemon Basil Pasta Sauce', 4.99, 95, 'Food - Sauces'),
  ('Cacao Nibs', 6.49, 24, 'Food - Baking'),
  ('Vintage Button-Down Shirt', 45.99, 45, 'Clothing - Shirts'),
  ('Electronic Drum Kit', 359.99, 44, 'Music'),
  ('Solar Garden Lights', 39.99, 31, 'Outdoor'),
  ('Sweet Potatoes', 0.89, 2, 'Food - Produce'),
  ('Kitchen Scale', 19.99, 23, 'Kitchen'),
  ('Vegetable Quinoa Bowl', 5.99, 76, 'Food - Frozen Meals'),
  ('Dried Cranberries', 4.29, 78, 'Food - Snacks'),
  ('Luxe Velvet Blazer', 89.99, 41, 'Clothing - Outerwear'),
  ('Classic Bagels', 2.99, 8, 'Food - Bakery'),
  ('Fitness Mat', 49.99, 97, 'Fitness'),
  ('Smart Wi-Fi Light Bulbs', 19.99, 46, 'Smart Home'),
  ('Silicone Stretch Lids', 14.99, 17, 'Kitchen'),
  ('Baking Soda', 0.99, 56, 'Food - Baking'),
  ('Nut Butter Cups', 3.99, 22, 'Food - Snacks'),
  ('Vegetable Fried Rice', 4.99, 100, 'Food - Frozen Foods');